# Generated by Django 2.0.9 on 2019-02-12 20:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190211_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=750),
            preserve_default=False,
        ),
    ]
