# Generated by Django 2.0.9 on 2019-02-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='desc',
            new_name='description',
        ),
    ]
